package com.inventory.tests;

import org.openqa.selenium.By;
import org.testng.annotations.Test;

import java.io.IOException;

public class CreateInventoryTest extends TestBase {

    public String newPiece = "Cabinet";
//create the transaction with type Pickup
    @Test
    public void createNewInventory() throws InterruptedException, IOException {
        app.clickOnTheCreateNewInventoryButton();
        app.type(By.id("inventory_name"),"Alisa2");
        app.type(By.id("inventory_id"), "10947-1-1");
        app.hideKeyboard();
        app.clickOnTheCreateButton();
        app.click_CubeSheet_button_onTheInventoriesScreen();
        app.clickOnTheAddPieceButton();
        app.selectLocationForTheNewPiece();
        app.selectPackageForNewPiece();
        app.selectPBOForNewPiece();
        app.swipeScreenDown();
        app.addItemIntoNewPiece3(newPiece);
        app.click_Item_OnPackageScreen_toOpenItemDetailsScreen();
        app.changeTypeOfNewItem();
        app.addConditionToTheNewItem();
        app.hideKeyboard();
        app.addCommentToTheNewItem();
        app.hideKeyboard();
        app.addCondition();
        app.addLocation();
        app.hideKeyboard();
        app.attachPhotoFromGallery();
        app.attachPhotoFromCamera();
        app.clickOnSavePhotoFromCamera();
        app.clickToTheReturnUpButton();
        app.clickToTheReturnUpButton();
        app.clickToTheReturnUpButton();
        app.swipeScreenToTheLeft();
        app.select_Room_withItem_inRoomsGrid_onRoomsScreen();
        app.click_InspectionInfo_button();
        app.fillDescriptionField();
        app.hideKeyboard();
        app.fillConditionField();
        app.hideKeyboard();
        app.attachPhotoFromGallery();
        app.attachPhotoConditions();
        app.clickOnSavePhotoFromCamera();
        app.selectPropertyBeforePacking();
        app.clickOnTheSelectConditionButtonOfPropertyBeforePacking();
        app.clickOnPropertyConditionsFieldAfterPacking();
        app.attachPhotoFromGallery();
        app.attachPhotoConditions();
        app.clickOnSavePhotoFromCamera();
        app.selectPropertyAfterPacking();
        app.clickOnTheSelectConditionButtonOfPropertyAfterPacking();
        app.clickToTheReturnUpButton();
        app.clickToTheReturnUpButton();
        app.swipeScreenToTheLeft();
        app.clickToAddSkidButton();
        app.swipeScreenDown();
        app.clickToTheSkidContentButton();
        app.clickToTheLoadSkidButton();
        app.clickToTheReturnUpButton();
        app.attachPhotoFromGallery();
        app.attachPhotoToTheNewSkid();
        app.clickOnSavePhotoFromCamera();
        app.clickToTheSkidOKButton();
        Thread.sleep(2000);
        app.click_NavigateMenu_button();
        app.clickOnTheSummaries();
        app.click_Packers_button_onNavigateMenu();
        app.clickToTheReturnUpButton();
        app.click_NavigateMenu_button();
        app.click_CartonsSummary_onNavigateMenu();
        app.clickToTheReturnUpButton();
        app.click_NavigateMenu_button();
        app.click_Appliances_onNavigateMenu();
        app.clickToTheReturnUpButton();
        app.click_NavigateMenu_button();
        app.swipeScreenDownMenu();
        app.click_AdditionalServices_button_onNavigateMenu();
        app.click_AdditionalMaterials_button_onNavigateMenu();
        app.clickToTheReturnUpButton();
        app.click_NavigateMenu_button();
        app.click_Services_button_onNavigateMenu();
        app.openServiceList();
        app.addServiceText();
        app.clickOnTheOKButton();
        app.addValueFromList();
        app.attachPhotoFromCameraToService();
        app.clickOnSavePhotoFromCamera();
        app.createSingnatureforAditionalService();
        app.clickToTheReturnUpButton();
        app.clickToTheReturnUpButton();
        app.click_NavigateMenu_button();
        app.click_AdditionalInfo__button_onNavigateMenu();
        app.openFirstPropertiesList();
        app.createSingnatureforAditionalService();
        app.clickToTheReturnUpButton();
        app.addQuestionText();
        app.clickOnTheOKButton();
        app.clickToTheReturnUpButton();
        app.click_NavigateMenu_button();
        app.swipeScreenDownMenu();
        app.click_Documents_button_onNavigateMenu();
        app.clickOnTheAddDocumentButton();
        app.fillDocumentNameField();
        app.hideKeyboard();
        app.attachPhotoToTheDocumentSectionFromGallery();
        Thread.sleep(2000);
        app.clickOnTheAddDocumentButton();
        app.fillDocumentNameField();
        app.hideKeyboard();
        app.attachPhotoToTheDocumentSection();
        app.clickOnSavePhotoFromCamera();
        app.clickOnTheDeviceReturnButton();
        app.click_NavigateMenu_button();
        app.swipeScreenDownMenu();
        app.clickToTheSignAndSendButton();
        app.swipeScreenDown();
        app.clickOnTheClientShipperButton();
        app.createSingnature2();
        app.clickToTheReturnUpButton();
        app.clickOnTheForemanDriverButton();
        app.createSingnature2();
        app.clickToTheReturnUpButton();
        app.swipeScreenUp();
        app.clickOnTheUploadButton();
        app.clickOnTheOKButtonOnThePopUp();
        app.screenshot();
        app.clickToTheReturnUpButton();
    }
}
